<a href="https://colab.research.google.com/github/Udayr777/Natural-Language-Processing/blob/main/FakeNewsClassifierUsingLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('train.csv')

In [4]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [5]:
df.shape

(20800, 5)

In [6]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [13]:
missing_values = df.isnull().sum()
missing_values

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [14]:
# percentage to callculate null values
import numpy as np
total_cells = np.product(df.shape)
total_cells

104000

In [20]:
# total missing values present in the dataset
total_missing_values = missing_values.sum()
total_missing_values

2554

In [18]:
# total percentage
percent = (total_missing_values/total_cells) * 100
percent

2.455769230769231

In [21]:
###Drop Nan Values
df=df.dropna()


In [22]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [23]:
df.shape

(18285, 5)

In [24]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [25]:
## Get the Independent Features
X=df.drop('label',axis=1)

In [26]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [27]:
## Get the Dependent features
y=df['label']

In [30]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [28]:
X.shape

(18285, 4)

In [29]:
y.shape

(18285,)

In [31]:
import tensorflow as tf

In [32]:
tf.__version__

'2.15.0'

In [35]:
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
### Vocabulary size
voc_size=10000

### Onehot Representation

In [36]:
messages=X.copy()

In [37]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [38]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [42]:
# messages.reset_index(inplace=True)

In [43]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [44]:
import nltk
import re
from nltk.corpus import stopwords

In [45]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [46]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [47]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [48]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [49]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[469, 3839, 9379, 5339, 4745, 2072, 5803, 1741, 157, 6993],
 [4056, 32, 3385, 5952, 3002, 4165, 8213],
 [9249, 5145, 6728, 6614],
 [7563, 2900, 5621, 1758, 5695, 2393],
 [5992, 3002, 3978, 2616, 9077, 384, 3002, 4346, 686, 4906],
 [7366,
  6831,
  7746,
  300,
  2386,
  1858,
  2312,
  3383,
  756,
  4544,
  9728,
  9534,
  2327,
  212,
  8213],
 [8565, 8847, 2699, 3542, 8591, 1383, 1630, 4288, 3864, 7790, 2347],
 [965, 6907, 4187, 759, 9685, 3629, 1858, 2384, 3864, 7790, 2347],
 [6353, 9088, 4650, 1996, 2972, 7420, 3602, 4892, 1858, 9935],
 [8371, 8930, 6242, 5847, 5952, 2430, 9963, 6134],
 [6440, 7098, 3615, 4549, 1783, 5086, 7127, 6247, 3322, 2690, 3578],
 [1758, 4570, 4745, 7420, 1858, 9685],
 [2543, 9239, 2894, 295, 406, 3178, 2116, 2486, 3470],
 [1712, 907, 9321, 261, 5328, 222, 7469, 3864, 7790, 2347],
 [5950, 5170, 6053, 4599, 6478, 3864, 7790, 2347],
 [499, 1243, 6641, 8477, 1121, 6279, 5706, 3734, 5819, 3706],
 [2005, 4192, 32],
 [1564, 8866, 9884, 3593, 1858, 5310, 884, 821

In [50]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [51]:
onehot_repr[1]

[4056, 32, 3385, 5952, 3002, 4165, 8213]

### Embedding Representation

In [52]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[ 469 3839 9379 ...    0    0    0]
 [4056   32 3385 ...    0    0    0]
 [9249 5145 6728 ...    0    0    0]
 ...
 [5530  484 6969 ...    0    0    0]
 [2324 9685 4625 ...    0    0    0]
 [5078 4566 3388 ...    0    0    0]]


In [53]:
embedded_docs[1]

array([4056,   32, 3385, 5952, 3002, 4165, 8213,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [54]:
embedded_docs[0]

array([ 469, 3839, 9379, 5339, 4745, 2072, 5803, 1741,  157, 6993,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [59]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            400000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 456501 (1.74 MB)
Trainable params: 456501 (1.74 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [60]:
len(embedded_docs),y.shape

(18285, (18285,))

In [61]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [62]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [75]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=20,batch_size=64)

Epoch 1/20
192/192 [==============================] - 13s 51ms/step - loss: 0.3283 - accuracy: 0.8355 - val_loss: 0.2003 - val_accuracy: 0.9160
Epoch 2/20
192/192 [==============================] - 3s 14ms/step - loss: 0.1316 - accuracy: 0.9496 - val_loss: 0.2016 - val_accuracy: 0.9256
Epoch 3/20
192/192 [==============================] - 2s 10ms/step - loss: 0.0821 - accuracy: 0.9720 - val_loss: 0.2283 - val_accuracy: 0.9171
Epoch 4/20
192/192 [==============================] - 2s 10ms/step - loss: 0.0517 - accuracy: 0.9823 - val_loss: 0.2875 - val_accuracy: 0.9220
Epoch 5/20
192/192 [==============================] - 3s 14ms/step - loss: 0.0419 - accuracy: 0.9866 - val_loss: 0.3160 - val_accuracy: 0.9065
Epoch 6/20
192/192 [==============================] - 2s 11ms/step - loss: 0.0281 - accuracy: 0.9914 - val_loss: 0.3616 - val_accuracy: 0.9147
Epoch 7/20
192/192 [==============================] - 2s 8ms/step - loss: 0.0242 - accuracy: 0.9927 - val_loss: 0.3807 - val_accuracy: 0.9120

### Adding Dropout for increase the accuracy and reduce overfitting

In [71]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [76]:
y_pred=model.predict(X_test)

189/189 [==============================] - 0s 2ms/step


In [77]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [78]:
from sklearn.metrics import confusion_matrix

In [79]:
confusion_matrix(y_test,y_pred)

array([[3155,  264],
       [ 311, 2305]])

In [80]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9047224523612262

In [81]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.92      0.92      3419
           1       0.90      0.88      0.89      2616

    accuracy                           0.90      6035
   macro avg       0.90      0.90      0.90      6035
weighted avg       0.90      0.90      0.90      6035

