<a href="https://colab.research.google.com/github/Udayr777/Natural-Language-Processing/blob/main/WomenClothing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# importing libraries
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Womens.csv')
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [4]:
#checking null values
null_values = df.isnull().sum()
null_values

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [5]:
# total null values
total_null = null_values.sum()
total_null

4697

In [6]:
# total values in the dataset
total_values = np.product(df.shape)
total_values

258346

In [7]:
# cal the percent of missing values
percent = (total_null / total_values) * 100
percent

1.8181044026228392

In [8]:
df.shape

(23486, 11)

In [9]:
text_df = df.dropna()
text_df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   
5           5         1080   49  Not for the very petite   
6           6          858   39     Cagrcoal shimmer fun   

                                         Review Text  Rating  Recommended IND  \
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   
5  I love tracy reese dresses, but this one is no...       2                0   
6  I aded this in my basket at hte last mintue to...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses  
5                        4         General         Dresses    Dresses  
6                        1  General Petite            Tops      Knits

In [10]:
text_df.shape

(19662, 11)

In [11]:
text_df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   
5           5         1080   49  Not for the very petite   
6           6          858   39     Cagrcoal shimmer fun   

                                         Review Text  Rating  Recommended IND  \
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   
5  I love tracy reese dresses, but this one is no...       2                0   
6  I aded this in my basket at hte last mintue to...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses  
5                        4         General         Dresses    Dresses  
6                        1  General Petite            Tops      Knits

In [20]:
X = text_df[['Title', 'Review Text']]
X

Title  \
2                                Some major design flaws   
3                                       My favorite buy!   
4                                       Flattering shirt   
5                                Not for the very petite   
6                                   Cagrcoal shimmer fun   
...                                                  ...   
23481                     Great dress for many occasions   
23482                         Wish it was made of cotton   
23483                              Cute, but see through   
23484  Very cute dress, perfect for summer parties an...   
23485                    Please make more like this one!   

                                             Review Text  
2      I had such high hopes for this dress and reall...  
3      I love, love, love this jumpsuit. it's fun, fl...  
4      This shirt is very flattering to all due to th...  
5      I love tracy reese dresses, but this one is no...  
6      I aded this in my basket at hte last mintue to...  
...                                                  ...  
23481  I was very happy to snag this dress at such a ...  
23482  It reminds me of maternity clothes. soft, stre...  
23483  This fit well, but the top was very see throug...  
23484  I bought this dress for a wedding i have this ...  
23485  This dress in a lovely platinum is feminine an...  

[19662 rows x 2 columns]

In [21]:
X.shape

(19662, 2)

In [23]:
X.isnull().sum()

Title          0
Review Text    0
dtype: int64

In [24]:
y = text_df['Recommended IND']
y.head()

2    0
3    1
4    1
5    0
6    1
Name: Recommended IND, dtype: int64

In [27]:
import nltk
from nltk.stem import WordNetLemmatizer
import re
from nltk.corpus import stopwords

In [28]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [33]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [26]:
lemmatizer = WordNetLemmatizer()

In [38]:
text_df['Review Text']

2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
5        I love tracy reese dresses, but this one is no...
6        I aded this in my basket at hte last mintue to...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 19662, dtype: object

In [39]:
corpus = []
for i in text_df.index:
  review = re.sub('[^a-zA-Z]', ' ',text_df['Review Text'][i])
  review = review.lower()
  review = review.split()
  review = [lemmatizer.lemmatize(words) for words in review if not words in stopwords.words('english') ]
  review = ' '.join(review)
  corpus.append(review)

In [40]:
corpus

['high hope dress really wanted work initially ordered petite small usual size found outrageously small small fact could zip reordered petite medium ok overall top half comfortable fit nicely bottom half tight layer several somewhat cheap net layer imo major design flaw net layer sewn directly zipper c',
 'love love love jumpsuit fun flirty fabulous every time wear get nothing great compliment',
 'shirt flattering due adjustable front tie perfect length wear legging sleeveless pair well cardigan love shirt',
 'love tracy reese dress one petite foot tall usually wear p brand dress pretty package lot dress skirt long full overwhelmed small frame stranger alteration shortening narrowing skirt would take away embellishment garment love color idea style work returned dress',
 'aded basket hte last mintue see would look like person store pick went teh darkler color pale hte color really gorgeous turn mathced everythiing trying prefectly little baggy hte x hte msallet size bummer petite decid

In [41]:
import tensorflow as tf
from tensorflow.keras.layers import LSTM, Embedding, Dense, Bidirectional
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot


In [42]:
# vocabulary size
voc_size = 10000

In [43]:
# converting words to vector embedding
one_hot = [ one_hot(word, voc_size) for word in corpus]
one_hot

[[8742,
  9051,
  8899,
  6120,
  1181,
  2212,
  4428,
  2235,
  4406,
  7488,
  2595,
  949,
  8372,
  898,
  7488,
  7488,
  7035,
  9170,
  7419,
  1048,
  4406,
  4411,
  1311,
  1482,
  6866,
  5273,
  8677,
  7645,
  4172,
  6871,
  5273,
  4622,
  9335,
  4923,
  6107,
  3728,
  9051,
  9335,
  9111,
  577,
  893,
  3324,
  9051,
  9335,
  6129,
  40,
  7551,
  1905],
 [6867,
  6867,
  6867,
  3354,
  6690,
  2214,
  4588,
  515,
  3785,
  4953,
  1954,
  2885,
  1684,
  4020],
 [487,
  5118,
  5396,
  8828,
  8494,
  6693,
  6050,
  6998,
  4953,
  1216,
  7237,
  3377,
  127,
  8672,
  6867,
  487],
 [6867,
  3775,
  6989,
  8899,
  2246,
  4406,
  9499,
  7176,
  2758,
  4953,
  6866,
  2190,
  8899,
  6525,
  8757,
  5108,
  8899,
  5486,
  4023,
  7207,
  1173,
  7488,
  7833,
  6750,
  8038,
  4154,
  3193,
  5486,
  8653,
  5620,
  5742,
  4250,
  2540,
  6867,
  9662,
  8559,
  2986,
  2212,
  2433,
  8899],
 [2260,
  68,
  9548,
  2696,
  8738,
  4498,
  8653,
  280,
 

In [44]:
one_hot[0]

[8742,
 9051,
 8899,
 6120,
 1181,
 2212,
 4428,
 2235,
 4406,
 7488,
 2595,
 949,
 8372,
 898,
 7488,
 7488,
 7035,
 9170,
 7419,
 1048,
 4406,
 4411,
 1311,
 1482,
 6866,
 5273,
 8677,
 7645,
 4172,
 6871,
 5273,
 4622,
 9335,
 4923,
 6107,
 3728,
 9051,
 9335,
 9111,
 577,
 893,
 3324,
 9051,
 9335,
 6129,
 40,
 7551,
 1905]

In [45]:
# embedding representation
sent_length = 300
embedding_rep = pad_sequences(one_hot, padding='pre',maxlen=sent_length)
embedding_rep

array([[   0,    0,    0, ...,   40, 7551, 1905],
       [   0,    0,    0, ..., 2885, 1684, 4020],
       [   0,    0,    0, ..., 8672, 6867,  487],
       ...,
       [   0,    0,    0, ..., 3246, 8653, 1684],
       [   0,    0,    0, ..., 7093, 3480, 4544],
       [   0,    0,    0, ...,  152,  797, 1747]], dtype=int32)

In [47]:
# creating the model
embedding_features = 400
model = Sequential()
model.add(Embedding(
    voc_size,
    embedding_features,
    input_length = sent_length
))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(
    1, activation = 'sigmoid'
))

In [48]:
model.compile(
    loss = 'binary_crossentropy',
    optimizer = 'adam',
    metrics = ['accuracy']
)

In [49]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 300, 400)          4000000   
                                                                 
 bidirectional_1 (Bidirecti  (None, 200)               400800    
 onal)                                                           
                                                                 
 dense (Dense)               (None, 1)                 201       
                                                                 
Total params: 4401001 (16.79 MB)
Trainable params: 4401001 (16.79 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [50]:
# converting embedding docs to array
X_final = np.array(embedding_rep)
X_final

array([[   0,    0,    0, ...,   40, 7551, 1905],
       [   0,    0,    0, ..., 2885, 1684, 4020],
       [   0,    0,    0, ..., 8672, 6867,  487],
       ...,
       [   0,    0,    0, ..., 3246, 8653, 1684],
       [   0,    0,    0, ..., 7093, 3480, 4544],
       [   0,    0,    0, ...,  152,  797, 1747]], dtype=int32)

In [51]:
y_final = np.array(y)
y_final

array([0, 1, 1, ..., 0, 1, 1])

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.20, random_state=42)

In [54]:
# model training
model.fit(X_train, y_train,
          validation_data = (X_test, y_test),
          epochs = 2,
          batch_size = 32,
          verbose = True)

Epoch 1/2
492/492 [==============================] - 718s 1s/step - loss: 0.1636 - accuracy: 0.9359 - val_loss: 0.2873 - val_accuracy: 0.8863
Epoch 2/2
492/492 [==============================] - 707s 1s/step - loss: 0.1225 - accuracy: 0.9542 - val_loss: 0.3225 - val_accuracy: 0.8708


In [56]:
y_pred = model.predict(X_test)
y_pred

123/123 [==============================] - 54s 441ms/step


array([[0.51949924],
       [0.72876406],
       [0.24924125],
       ...,
       [0.05828245],
       [0.93287945],
       [0.7965145 ]], dtype=float32)

In [57]:
y_pred = np.where(y_pred>= 0.5, 1, 0)
y_pred

array([[1],
       [1],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, y_pred)

0.8708365115687771

In [59]:
confusion_matrix(y_test, y_pred)

array([[ 500,  200],
       [ 308, 2925]])