<a href="https://colab.research.google.com/github/Udayr777/Natural-Language-Processing/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [13]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [12]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[229, 191, 222, 425], [229, 191, 222, 454], [229, 238, 222, 123], [270, 334, 489, 335, 431], [270, 334, 489, 335, 177], [65, 229, 355, 222, 483], [493, 392, 414, 335]]


### Word Embedding Represntation

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [15]:
import numpy as np

In [17]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 229 191 222 425]
 [  0   0   0   0 229 191 222 454]
 [  0   0   0   0 229 238 222 123]
 [  0   0   0 270 334 489 335 431]
 [  0   0   0 270 334 489 335 177]
 [  0   0   0  65 229 355 222 483]
 [  0   0   0   0 493 392 414 335]]


In [18]:
## 10 feature dimesnions
dim=10


In [19]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 229, 191, 222, 425], dtype=int32)

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 108ms/step


array([[-0.02712992, -0.00574459, -0.01620636,  0.01253426, -0.02226467,
        -0.0235961 ,  0.01786108,  0.00850832, -0.01407349,  0.0260019 ],
       [-0.02712992, -0.00574459, -0.01620636,  0.01253426, -0.02226467,
        -0.0235961 ,  0.01786108,  0.00850832, -0.01407349,  0.0260019 ],
       [-0.02712992, -0.00574459, -0.01620636,  0.01253426, -0.02226467,
        -0.0235961 ,  0.01786108,  0.00850832, -0.01407349,  0.0260019 ],
       [-0.02712992, -0.00574459, -0.01620636,  0.01253426, -0.02226467,
        -0.0235961 ,  0.01786108,  0.00850832, -0.01407349,  0.0260019 ],
       [ 0.03890142,  0.04666081,  0.0314664 ,  0.00524656,  0.01520247,
         0.04947864, -0.03425844,  0.04591518,  0.0474276 , -0.02516778],
       [-0.02327623, -0.03799541, -0.03149052, -0.04492193, -0.00869273,
         0.0232548 , -0.03962464,  0.04858536,  0.01799121,  0.02413202],
       [ 0.04854223, -0.03514119,  0.01623863, -0.01435591,  0.00526404,
         0.0459924 ,  0.040005  , -0.00304734

In [23]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 42ms/step
[[[-0.02712992 -0.00574459 -0.01620636  0.01253426 -0.02226467
   -0.0235961   0.01786108  0.00850832 -0.01407349  0.0260019 ]
  [-0.02712992 -0.00574459 -0.01620636  0.01253426 -0.02226467
   -0.0235961   0.01786108  0.00850832 -0.01407349  0.0260019 ]
  [-0.02712992 -0.00574459 -0.01620636  0.01253426 -0.02226467
   -0.0235961   0.01786108  0.00850832 -0.01407349  0.0260019 ]
  [-0.02712992 -0.00574459 -0.01620636  0.01253426 -0.02226467
   -0.0235961   0.01786108  0.00850832 -0.01407349  0.0260019 ]
  [ 0.03890142  0.04666081  0.0314664   0.00524656  0.01520247
    0.04947864 -0.03425844  0.04591518  0.0474276  -0.02516778]
  [-0.02327623 -0.03799541 -0.03149052 -0.04492193 -0.00869273
    0.0232548  -0.03962464  0.04858536  0.01799121  0.02413202]
  [ 0.04854223 -0.03514119  0.01623863 -0.01435591  0.00526404
    0.0459924   0.040005   -0.00304734  0.01604965 -0.01454344]
  [-0.00266994  0.02298622  0.04863676 -0.03665645 -0.00021

In [24]:
embedded_docs[0]

array([  0,   0,   0,   0, 229, 191, 222, 425], dtype=int32)

In [25]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 18ms/step
[[-0.02712992 -0.00574459 -0.01620636  0.01253426 -0.02226467 -0.0235961
   0.01786108  0.00850832 -0.01407349  0.0260019 ]
 [-0.02712992 -0.00574459 -0.01620636  0.01253426 -0.02226467 -0.0235961
   0.01786108  0.00850832 -0.01407349  0.0260019 ]
 [-0.02712992 -0.00574459 -0.01620636  0.01253426 -0.02226467 -0.0235961
   0.01786108  0.00850832 -0.01407349  0.0260019 ]
 [-0.02712992 -0.00574459 -0.01620636  0.01253426 -0.02226467 -0.0235961
   0.01786108  0.00850832 -0.01407349  0.0260019 ]
 [ 0.03890142  0.04666081  0.0314664   0.00524656  0.01520247  0.04947864
  -0.03425844  0.04591518  0.0474276  -0.02516778]
 [-0.02327623 -0.03799541 -0.03149052 -0.04492193 -0.00869273  0.0232548
  -0.03962464  0.04858536  0.01799121  0.02413202]
 [ 0.04854223 -0.03514119  0.01623863 -0.01435591  0.00526404  0.0459924
   0.040005   -0.00304734  0.01604965 -0.01454344]
 [-0.00266994  0.02298622  0.04863676 -0.03665645 -0.00021069 -0.01628724
  -0.

In [26]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [27]:
# vocabulary size
voc_size = 50000

In [28]:
# one hot encoding
one_hot_rep = [one_hot(words, voc_size) for words in sent]
one_hot_rep

[[35473, 16499, 20440, 37559, 33643, 27969],
 [44976, 40534, 20440, 20842, 47603, 44570],
 [3511, 16241, 31568, 49844],
 [35473, 1904, 20440, 4212, 35473, 21179],
 [7562, 37185, 5897, 20440, 20842, 47603, 44570],
 [49767, 20440, 20842, 47603, 49799, 34540]]

In [29]:
# fix the size by pre or post padding through embedding
sent_length = 10
embedding_doc = pad_sequences(one_hot_rep, padding="pre", maxlen=sent_length)
embedding_doc


array([[    0,     0,     0,     0, 35473, 16499, 20440, 37559, 33643,
        27969],
       [    0,     0,     0,     0, 44976, 40534, 20440, 20842, 47603,
        44570],
       [    0,     0,     0,     0,     0,     0,  3511, 16241, 31568,
        49844],
       [    0,     0,     0,     0, 35473,  1904, 20440,  4212, 35473,
        21179],
       [    0,     0,     0,  7562, 37185,  5897, 20440, 20842, 47603,
        44570],
       [    0,     0,     0,     0, 49767, 20440, 20842, 47603, 49799,
        34540]], dtype=int32)

In [30]:
# feature dimention
dim = 10

In [31]:
# model
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam','mse')

In [32]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            500000    
                                                                 
Total params: 500000 (1.91 MB)
Trainable params: 500000 (1.91 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [37]:
embedding_doc[4]

array([    0,     0,     0,  7562, 37185,  5897, 20440, 20842, 47603,
       44570], dtype=int32)

In [39]:
# checking the first sentence "Tom and Jerry is my favourite movie"
model.predict(embedding_doc[4])

1/1 [==============================] - 0s 34ms/step


array([[-0.00938592,  0.0273456 ,  0.04480506,  0.00932663,  0.00454557,
         0.03418673,  0.03093958, -0.0311322 ,  0.01075882,  0.02732182],
       [-0.00938592,  0.0273456 ,  0.04480506,  0.00932663,  0.00454557,
         0.03418673,  0.03093958, -0.0311322 ,  0.01075882,  0.02732182],
       [-0.00938592,  0.0273456 ,  0.04480506,  0.00932663,  0.00454557,
         0.03418673,  0.03093958, -0.0311322 ,  0.01075882,  0.02732182],
       [ 0.02034806, -0.02264832, -0.01190222,  0.00464703,  0.00764178,
         0.01092268, -0.02205676, -0.02203061,  0.03186834,  0.03407958],
       [ 0.04294896,  0.02421292,  0.00533862,  0.02099985, -0.04063731,
        -0.03251483,  0.02963021,  0.02980808,  0.00992445,  0.0027251 ],
       [-0.03655447, -0.04057068,  0.04627242, -0.02688386, -0.03097603,
         0.00839432,  0.01905538,  0.03215339,  0.02394151,  0.01156262],
       [-0.0039328 , -0.03358822, -0.02788284,  0.01026857, -0.02955714,
        -0.01236048,  0.03288512, -0.03885356

In [40]:
model.predict(embedding_doc)

1/1 [==============================] - 0s 34ms/step


array([[[-0.00938592,  0.0273456 ,  0.04480506,  0.00932663,
          0.00454557,  0.03418673,  0.03093958, -0.0311322 ,
          0.01075882,  0.02732182],
        [-0.00938592,  0.0273456 ,  0.04480506,  0.00932663,
          0.00454557,  0.03418673,  0.03093958, -0.0311322 ,
          0.01075882,  0.02732182],
        [-0.00938592,  0.0273456 ,  0.04480506,  0.00932663,
          0.00454557,  0.03418673,  0.03093958, -0.0311322 ,
          0.01075882,  0.02732182],
        [-0.00938592,  0.0273456 ,  0.04480506,  0.00932663,
          0.00454557,  0.03418673,  0.03093958, -0.0311322 ,
          0.01075882,  0.02732182],
        [ 0.0391327 ,  0.03137076,  0.00280545, -0.0049634 ,
          0.04895339,  0.02245181, -0.00836391,  0.00797359,
         -0.03151631, -0.0327997 ],
        [-0.04399553,  0.0147823 ,  0.02053929,  0.00027829,
         -0.00439291, -0.04815215, -0.03715066, -0.04544387,
         -0.03186785,  0.01670409],
        [-0.0039328 , -0.03358822, -0.02788284,  0.0